cdn_urls:
    stg: "https://github.com/oracle/magento-extension-cx-apps/releases/download"
    prod: "https://github.com/oracle/magento-extension-cx-apps/releases/download"

paths:
    build: "builds"
    module: "Oracle"
