cdn_urls:
    stg: "https://github.com/kumarmanishbit/composer-test/releases/download"
    prod: "https://github.com/kumarmanishbit/composer-test/releases/download"

paths:
    build: "builds"
    module: "Oracle"
